abstract: HTML Widget Catalyst Plugin
author: Sebastian Riedel
distribution_type: module
generated_by: Module::Install version 0.54
license: perl
name: Catalyst-Plugin-HTML-Widget
no_index:
  directory:
    - inc
    - t
requires:
  Catalyst: 5.5
  HTML::Widget: 0
  perl: 5.8.1
version: 1.1
